actions:
  '1':
    action: delete_indices
    description: remove INDEX_PREFIX indices
    options:
      ignore_empty_list: true
      timeout_override: null
      continue_if_exception: true
      disable_action: null
    filters:
      - filtertype: pattern
        kind: prefix
        value: INDEX_PREFIX
        exclude: null
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d'
        unit: days
        unit_count: UNIT_COUNT
        exclude: null
